// Generated by CoffeeScript 1.12.4
var end, now, print, printEvery, start, start_times, times;

start_times = {};

times = {};

now = function() {
  return new Date().getTime();
};

start = function(name) {
  return start_times[name] = now();
};

end = function(name) {
  var dt;
  dt = now() - start_times[name];
  times[name] || (times[name] = 0);
  return times[name] += dt;
};

print = function() {
  var name, results, t;
  console.log('[times]');
  results = [];
  for (name in times) {
    t = times[name];
    results.push(console.log('*', name, t));
  }
  return results;
};

printEvery = function(t) {
  return setInterval(print, t);
};

module.exports = {
  start: start,
  end: end,
  times: times,
  printEvery: printEvery
};
